[package]
name = "reactex-macro"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
syn = { version = "2.0.23", features = ["full"] }
quote = "1.0.21"
reactex-macro-core = { path = "../reactex-macro-core" }
