[package]
name = "sample_project"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reactex-core = { path = "../reactex-core" }
log4rs = { version = "1.2.0", features = ["pattern_encoder"] }
